### ISSUE TITLE
SSH Permission issue

### ISSUE THREAD

**Issue by oumukoro** [aptible/deploy-demo-app#30]
After following the steps outlined, I am having issues with the permissions for ssh. I've done everything else that works with git but it seems to have an issue with beta.aptible.com

Is there a way to resolve this? Thank you

**Comment by joshraker** [comment]
Please see the [`git` Push Permission Denied](https://deploy-docs.aptible.com/docs/permission-denied-git-push) troubleshooting documentation for help with this issue. If you need additional assistance or have any other questions regarding the usage of the Aptible platform I recommend posting in the [Aptible Community](https://community.aptible.com/) or contacting [Aptible Support](https://deploy-docs.aptible.com/docs/support) as these channels are more appropriate for such questions and are monitored more closely than GitHub issues.
